yaml change

diff --git a/.github/workflows/formula-test.yaml b/.github/workflows/formula-test.yaml
--- a/.github/workflows/formula-test.yaml
+++ b/.github/workflows/formula-test.yaml
@@ -65,7 +65,6 @@ jobs:
     - name: Build QEMU with OpenGL Core
       run: |
         # First create a modification to the epoxy.pc file to indicate it has EGL support
-        # This is needed because QEMU's build system checks for epoxy/egl.h via pkg-config
         EPOXY_PC="$(brew --prefix)/opt/qemu-virgl-deps/lib/qemu-virgl/pkgconfig/epoxy.pc"
         if [ -f "$EPOXY_PC" ]; then
           echo "Original epoxy.pc:"
@@ -89,31 +88,51 @@ jobs:
           cat "$EPOXY_PC"
         fi
         
-          # Create stub EGL header
-          cd source/qemu
-          mkdir -p include/epoxy
-          cat > include/epoxy/egl.h << 'EOH'
-          /* Stub EGL header for OpenGL Core build */
-          #ifndef EPOXY_EGL_H
-          #define EPOXY_EGL_H
-          typedef int EGLint;
-          typedef unsigned int EGLenum;
-          typedef void *EGLDisplay;
-          typedef void *EGLSurface;
-          typedef void *EGLContext;
-          typedef void *EGLConfig;
-          typedef unsigned int EGLBoolean;
-          #define EGL_FALSE 0
-          #define EGL_TRUE 1
-          #endif /* EPOXY_EGL_H */
-         EOH
+        # Create stub EGL header directly in the pkg-config include directory
+        EPOXY_INCLUDE_DIR="$(pkg-config --variable=includedir epoxy)"
+        sudo mkdir -p "${EPOXY_INCLUDE_DIR}/epoxy"
+        
+        # Create the EGL stub header using multiple echo statements instead of a heredoc
+        sudo bash -c 'echo "/* Stub EGL header for OpenGL Core build */" > ${EPOXY_INCLUDE_DIR}/epoxy/egl.h'
+        sudo bash -c 'echo "#ifndef EPOXY_EGL_H" >> ${EPOXY_INCLUDE_DIR}/epoxy/egl.h'
+        sudo bash -c 'echo "#define EPOXY_EGL_H" >> ${EPOXY_INCLUDE_DIR}/epoxy/egl.h'
+        sudo bash -c 'echo "typedef int EGLint;" >> ${EPOXY_INCLUDE_DIR}/epoxy/egl.h'
+        sudo bash -c 'echo "typedef unsigned int EGLenum;" >> ${EPOXY_INCLUDE_DIR}/epoxy/egl.h'
+        sudo bash -c 'echo "typedef void *EGLDisplay;" >> ${EPOXY_INCLUDE_DIR}/epoxy/egl.h'
+        sudo bash -c 'echo "typedef void *EGLSurface;" >> ${EPOXY_INCLUDE_DIR}/epoxy/egl.h'
+        sudo bash -c 'echo "typedef void *EGLContext;" >> ${EPOXY_INCLUDE_DIR}/epoxy/egl.h'
+        sudo bash -c 'echo "typedef void *EGLConfig;" >> ${EPOXY_INCLUDE_DIR}/epoxy/egl.h'
+        sudo bash -c 'echo "typedef unsigned int EGLBoolean;" >> ${EPOXY_INCLUDE_DIR}/epoxy/egl.h'
+        sudo bash -c 'echo "#define EGL_FALSE 0" >> ${EPOXY_INCLUDE_DIR}/epoxy/egl.h'
+        sudo bash -c 'echo "#define EGL_TRUE 1" >> ${EPOXY_INCLUDE_DIR}/epoxy/egl.h'
+        sudo bash -c 'echo "#endif /* EPOXY_EGL_H */" >> ${EPOXY_INCLUDE_DIR}/epoxy/egl.h'
+        
+        # Also create stub header in QEMU source directory for CFLAGS
+        cd source/qemu
+        mkdir -p include/epoxy
+        
+        # Create the EGL stub header using echo statements
+        echo "/* Stub EGL header for OpenGL Core build */" > include/epoxy/egl.h
+        echo "#ifndef EPOXY_EGL_H" >> include/epoxy/egl.h
+        echo "#define EPOXY_EGL_H" >> include/epoxy/egl.h
+        echo "typedef int EGLint;" >> include/epoxy/egl.h
+        echo "typedef unsigned int EGLenum;" >> include/epoxy/egl.h
+        echo "typedef void *EGLDisplay;" >> include/epoxy/egl.h
+        echo "typedef void *EGLSurface;" >> include/epoxy/egl.h
+        echo "typedef void *EGLContext;" >> include/epoxy/egl.h
+        echo "typedef void *EGLConfig;" >> include/epoxy/egl.h
+        echo "typedef unsigned int EGLBoolean;" >> include/epoxy/egl.h
+        echo "#define EGL_FALSE 0" >> include/epoxy/egl.h
+        echo "#define EGL_TRUE 1" >> include/epoxy/egl.h
+        echo "#endif /* EPOXY_EGL_H */" >> include/epoxy/egl.h
         
         # Then run the build script with verbosity for debugging
+        set +e  # Don't exit on error
         PKG_CONFIG_PATH="$(brew --prefix)/opt/qemu-virgl-deps/lib/qemu-virgl/pkgconfig:$PKG_CONFIG_PATH" \
         compile-qemu-virgl source/qemu --opengl-core
+        COMPILE_RESULT=$?
         
-        # If the script fails, try manual configuration with more debug info
-        if [ $? -ne 0 ]; then
+        if [ $COMPILE_RESULT -ne 0 ]; then
           echo "=== Standard build failed, trying manual build with more debugging ==="
           cd source/qemu
           
@@ -130,7 +149,12 @@ jobs:
           # Configure with explicit flags and debugging
           CFLAGS="-I../include" ../configure --disable-egl --enable-opengl --enable-virglrenderer
           
-          # Build with make
+          # Build with make - this is the missing step that actually needs to run
+          make -j$(sysctl -n hw.ncpu)
+        else
+          # This part was missing - when configure succeeds, we still need to build!
+          cd source/qemu/build
+          echo "Configuration successful, now building QEMU..."
           make -j$(sysctl -n hw.ncpu)
         fi
 
